@startuml
[spring boot] as SB
component [spring mvc] as mvc #Green
note left of mvc 
这次要说的
end note
[spring beans] as beans
[spring web] as web
[spring context] as ctx
SB --> ctx: 配置
mvc --> ctx: 使用

ctx --> beans: 包含
mvc --> web: 调用
@enduml